//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCalisan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calisan
    {
        public int calisanID { get; set; }
        public string calisanIsim { get; set; }
        public string calisanAdres { get; set; }
        public Nullable<int> calisanYas { get; set; }
        public Nullable<decimal> calisanMaas { get; set; }
        public string calisanTelefon { get; set; }
        public string calisanEmail { get; set; }
        public int departmanID { get; set; }
        public int pozisyonID { get; set; }
        public string calisanKod { get; set; }
        public Nullable<int> calisanYetkiID { get; set; }
    
        public virtual Departman Departman { get; set; }
        public virtual Pozisyon Pozisyon { get; set; }
    }
}
